site/app/urls.py
# URLs
from django.conf.urls import patterns, url

# Views
from app import views

urlpatterns = patterns('',

    # log
    url(r'^$', views.index, name='index'), # / (index)
    url(r'^data/$', views.data, name='data'), # data/ (data)
)

site/demo/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^', include('app.urls', namespace="app")), # app
    url(r'^admin/', include(admin.site.urls)), # admin
)

site/app/models.py
from django.db import models

# Datatypes
from site_packages import timezone as timezone

# Timecard
class Timecard(models.Model):
    duration = models.IntegerField() # duration in seconds
    timestamp_start = models.DateTimeField() # timestamp_start
    timestamp_end = models.DateTimeField() # timestamp_end
    def __unicode__(self):
        return u"%s" % self.id

site/app/views.py
# App
from app.models import *

# Datatypes
import json
from datetime import date

# Render
from django.shortcuts import render, Http404
from django.http import HttpResponse

# Root
# + Root
def index(request):
    log = Timecard.objects.all()
    context = {'log': log}
    return render(request, 'index.html', context)
# + Data
def data(request):
    if request.is_ajax():
        data = list(Timecard.objects.values_list('duration', 'timestamp_start').order_by('timestamp_start'))
        return HttpResponse(json.dumps(data, default=date_handler), content_type='application/json')
    else:
        raise Http404

# Extra
# + Date Handler
def date_handler(obj):
    return obj.isoformat() if hasattr(obj, 'isoformat') else obj

site/app/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
    	<meta name="viewport" content="width=420">
        <meta name="author" content="Michael Young">

        {% load staticfiles %}

        <!-- Third-party JS files -->
        <script src="{% static "js/jquery-1.11.1.min.js" %}"></script>
        <script src="{% static "bootstrap/js/bootstrap.min.js" %}"></script>

        <!-- Third-party CSS files -->
        <link href="{% static "bootstrap/css/bootstrap.min.css" %}" rel="stylesheet">

        <!-- Globally applied CSS files -->
        <link rel="stylesheet" href="{% static "css/css.css" %}">
        <link rel="stylesheet" href="{% static "css/navbar.css" %}">
    </head>
    <body>
        {% block content %}
            Empty page
        {% endblock %}

        <!-- Navigation bar, load with low priority -->
        <nav class="demo navbar navbar-fixed-top"><div class="container"><div class="navbar-header"><a class="navbar-brand" href="{% url 'app:index' %}">Demo</a></div></div></nav>
    </body>
</html>

site/app/templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% load templatetags %}
{% block content %}
    <script src="{% static "js/highcharts.js" %}"></script>
    <script src="{% static "js/chart.js" %}"></script>
    <div class="container top">
        <div class="row-fluid">
            <div class="col-sm-12" style="margin-bottom: 19px">
                <h1>Log</h1>
            </div>
        </div>
        <div class="row-fluid">
            <div class="col-sm-12"><div id="log-graph" style="border: 1px solid #c0c0c0; height: 400px; margin-bottom: 19px"></div></div>
        </div>
        <div class="row-fluid">
            <div class="col-sm-12" style="margin-top: 19px">
                <table class="table table-responsive table-striped table-bordered">
                    <thead><tr><th>#</th><th>Duration (sec)</th><th>Start</th><th>End</th></tr></thead>
                    <tbody>
                        {% for item in log %}
                            <tr><td>{{ item.id }}</td><td>{{  item.duration }}</td><td>{{ item.timestamp_start|add_hours:'4' }}</td><td>{{ item.timestamp_end|add_hours:'4' }}</td></tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}